package dev.f4ls3.cloudsystem.eventbus;

public enum EventType {

    PACKET_SERVER_DECODE_PACKET_EVENT,
    PACKET_SERVER_ENCODE_PACKET_EVENT,
    PACKET_SERVER_CHANNEL_ACTIVE_EVENT,
    PACKET_SERVER_CHANNEL_INACTIVE_EVENT,
    PACKET_SERVER_PACKET_RECEIVED_EVENT
}
